// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (o *Order) Requester(ctx context.Context) (*User, error) {
	result, err := o.Edges.RequesterOrErr()
	if IsNotLoaded(err) {
		result, err = o.QueryRequester().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (o *Order) Receiver(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = o.NamedReceiver(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = o.Edges.ReceiverOrErr()
	}
	if IsNotLoaded(err) {
		result, err = o.QueryReceiver().All(ctx)
	}
	return result, err
}

func (u *User) Requested(
	ctx context.Context, after *Cursor, first *int, before *Cursor, last *int, orderBy *OrderOrder, where *OrderWhereInput,
) (*OrderConnection, error) {
	opts := []OrderPaginateOption{
		WithOrderOrder(orderBy),
		WithOrderFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[0][alias]
	if nodes, err := u.NamedRequested(alias); err == nil || hasTotalCount {
		pager, err := newOrderPager(opts, last != nil)
		if err != nil {
			return nil, err
		}
		conn := &OrderConnection{Edges: []*OrderEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, after, first, before, last)
		return conn, nil
	}
	return u.QueryRequested().Paginate(ctx, after, first, before, last, opts...)
}

func (u *User) Received(ctx context.Context) (result []*Order, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedReceived(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.ReceivedOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryReceived().All(ctx)
	}
	return result, err
}
