// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"shira-chan-dev/ent/order"
	"shira-chan-dev/ent/user"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (o *OrderQuery) CollectFields(ctx context.Context, satisfies ...string) (*OrderQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return o, nil
	}
	if err := o.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return o, nil
}

func (o *OrderQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(order.Columns))
		selectedFields = []string{order.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "requester":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: o.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			o.withRequester = query
		case "receives":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UserClient{config: o.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, mayAddCondition(satisfies, userImplementors)...); err != nil {
				return err
			}
			o.WithNamedReceives(alias, func(wq *UserQuery) {
				*wq = *query
			})
		case "title":
			if _, ok := fieldSeen[order.FieldTitle]; !ok {
				selectedFields = append(selectedFields, order.FieldTitle)
				fieldSeen[order.FieldTitle] = struct{}{}
			}
		case "content":
			if _, ok := fieldSeen[order.FieldContent]; !ok {
				selectedFields = append(selectedFields, order.FieldContent)
				fieldSeen[order.FieldContent] = struct{}{}
			}
		case "contact":
			if _, ok := fieldSeen[order.FieldContact]; !ok {
				selectedFields = append(selectedFields, order.FieldContact)
				fieldSeen[order.FieldContact] = struct{}{}
			}
		case "type":
			if _, ok := fieldSeen[order.FieldType]; !ok {
				selectedFields = append(selectedFields, order.FieldType)
				fieldSeen[order.FieldType] = struct{}{}
			}
		case "status":
			if _, ok := fieldSeen[order.FieldStatus]; !ok {
				selectedFields = append(selectedFields, order.FieldStatus)
				fieldSeen[order.FieldStatus] = struct{}{}
			}
		case "evaluation":
			if _, ok := fieldSeen[order.FieldEvaluation]; !ok {
				selectedFields = append(selectedFields, order.FieldEvaluation)
				fieldSeen[order.FieldEvaluation] = struct{}{}
			}
		case "hopeAt":
			if _, ok := fieldSeen[order.FieldHopeAt]; !ok {
				selectedFields = append(selectedFields, order.FieldHopeAt)
				fieldSeen[order.FieldHopeAt] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[order.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, order.FieldCreatedAt)
				fieldSeen[order.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[order.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, order.FieldUpdatedAt)
				fieldSeen[order.FieldUpdatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		o.Select(selectedFields...)
	}
	return nil
}

type orderPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OrderPaginateOption
}

func newOrderPaginateArgs(rv map[string]any) *orderPaginateArgs {
	args := &orderPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case map[string]any:
			var (
				err1, err2 error
				order      = &OrderOrder{Field: &OrderOrderField{}, Direction: entgql.OrderDirectionAsc}
			)
			if d, ok := v[directionField]; ok {
				err1 = order.Direction.UnmarshalGQL(d)
			}
			if f, ok := v[fieldField]; ok {
				err2 = order.Field.UnmarshalGQL(f)
			}
			if err1 == nil && err2 == nil {
				args.opts = append(args.opts, WithOrderOrder(order))
			}
		case *OrderOrder:
			if v != nil {
				args.opts = append(args.opts, WithOrderOrder(v))
			}
		}
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (u *UserQuery) CollectFields(ctx context.Context, satisfies ...string) (*UserQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return u, nil
	}
	if err := u.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return u, nil
}

func (u *UserQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(user.Columns))
		selectedFields = []string{user.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "requests":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrderClient{config: u.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, mayAddCondition(satisfies, orderImplementors)...); err != nil {
				return err
			}
			u.WithNamedRequests(alias, func(wq *OrderQuery) {
				*wq = *query
			})
		case "receiver":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrderClient{config: u.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, mayAddCondition(satisfies, orderImplementors)...); err != nil {
				return err
			}
			u.WithNamedReceiver(alias, func(wq *OrderQuery) {
				*wq = *query
			})
		case "uname":
			if _, ok := fieldSeen[user.FieldUname]; !ok {
				selectedFields = append(selectedFields, user.FieldUname)
				fieldSeen[user.FieldUname] = struct{}{}
			}
		case "phone":
			if _, ok := fieldSeen[user.FieldPhone]; !ok {
				selectedFields = append(selectedFields, user.FieldPhone)
				fieldSeen[user.FieldPhone] = struct{}{}
			}
		case "wechat":
			if _, ok := fieldSeen[user.FieldWechat]; !ok {
				selectedFields = append(selectedFields, user.FieldWechat)
				fieldSeen[user.FieldWechat] = struct{}{}
			}
		case "level":
			if _, ok := fieldSeen[user.FieldLevel]; !ok {
				selectedFields = append(selectedFields, user.FieldLevel)
				fieldSeen[user.FieldLevel] = struct{}{}
			}
		case "dept":
			if _, ok := fieldSeen[user.FieldDept]; !ok {
				selectedFields = append(selectedFields, user.FieldDept)
				fieldSeen[user.FieldDept] = struct{}{}
			}
		case "state":
			if _, ok := fieldSeen[user.FieldState]; !ok {
				selectedFields = append(selectedFields, user.FieldState)
				fieldSeen[user.FieldState] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[user.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, user.FieldCreatedAt)
				fieldSeen[user.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[user.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, user.FieldUpdatedAt)
				fieldSeen[user.FieldUpdatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		u.Select(selectedFields...)
	}
	return nil
}

type userPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []UserPaginateOption
}

func newUserPaginateArgs(rv map[string]any) *userPaginateArgs {
	args := &userPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case map[string]any:
			var (
				err1, err2 error
				order      = &UserOrder{Field: &UserOrderField{}, Direction: entgql.OrderDirectionAsc}
			)
			if d, ok := v[directionField]; ok {
				err1 = order.Direction.UnmarshalGQL(d)
			}
			if f, ok := v[fieldField]; ok {
				err2 = order.Field.UnmarshalGQL(f)
			}
			if err1 == nil && err2 == nil {
				args.opts = append(args.opts, WithUserOrder(order))
			}
		case *UserOrder:
			if v != nil {
				args.opts = append(args.opts, WithUserOrder(v))
			}
		}
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

func limitRows(partitionBy string, limit int, orderBy ...sql.Querier) func(s *sql.Selector) {
	return func(s *sql.Selector) {
		d := sql.Dialect(s.Dialect())
		s.SetDistinct(false)
		with := d.With("src_query").
			As(s.Clone()).
			With("limited_query").
			As(
				d.Select("*").
					AppendSelectExprAs(
						sql.RowNumber().PartitionBy(partitionBy).OrderExpr(orderBy...),
						"row_number",
					).
					From(d.Table("src_query")),
			)
		t := d.Table("limited_query").As(s.TableName())
		*s = *d.Select(s.UnqualifiedColumns()...).
			From(t).
			Where(sql.LTE(t.C("row_number"), limit)).
			Prefix(with)
	}
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
